spring:
  application:
    name: OpenGroup
  profiles:
    active: homologacao
  thymeleaf:
    check-template-location: false

server:
  port: 80

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    supported-submit-methods: { "get", "put", "post", "delete", "options", "head", "patch", "trace"}

  api-docs:
    enabled: true